### ISSUE TITLE
Website Updates

### ISSUE THREAD

**Issue by maciejmatu** [Joystream/joystream-org#47]
Tasks to be done:
- [ ] Rome testnet page (#48)
- [x] Manifesto page (#51)
- [x] Fix warnings in tests (#49)
- [ ] UI updates and fixes (#51)
- [ ] Change Footer component (#51)

**Comment by blrhc** [comment]
@maciejmatu Is this up-to-date?

**Comment by maciejmatu** [comment]
@blrhc Yes. Theoretically all of them should be checked because I finished them and opened PR's, but I'm waiting until everything i merged to mark them as done
